name: submission
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  camera: ^0.12.0+1
  flutter:
    sdk: flutter

  image: ^4.8.0
  image_cropper: ^12.1.1
  image_picker: ^1.2.1
  provider: ^6.1.2
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ml_model/1.tflite
    - assets/ml_model/probability-labels-en.txt
    - assets/rendang.png

fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        weight: 700
      - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        weight: 500
      - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        weight: 400
      - asset: assets/fonts/Manrope/Manrope-Light.ttf
        weight: 300
      - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        weight: 200
